import "server-only";
/**
 * ManualInvoice adapter — the PRIMARY adapter for the real business (WP-13).
 *
 * SecureVoice bills UAE banks and exchange houses that pay by bank transfer
 * against a quote. There is no gateway to call, no webhook to verify, and no
 * amount of signature verification that substitutes for a human being who has
 * looked at the bank statement. So the trust boundary is moved: instead of a
 * cryptographic proof of payment, we require **dual control**.
 *
 *   1. `recordPayment` — operator A enters the transfer reference and amount.
 *      Row lands as `pending`. No units are credited.
 *   2. `verifyPayment` — operator B confirms the money actually arrived.
 *      **A may not verify their own entry**: that single rule is what stops one
 *      compromised or careless login from minting entitlements.
 *      Row becomes `success`, units are credited via the ledger.
 *
 * The recorder identity lives in `PaymentRecord.entitlementsJson` (see
 * `EntitlementEnvelope` in `provider.ts`), NOT in process memory — dual control
 * that evaporates on restart is not dual control.
 *
 * Both steps append to the tamper-evident audit chain (`src/lib/audit-chain.ts`)
 * under a shared `PAY-{reference}` callRef, so the record and the verification
 * are chained together and `verifyChain()` covers both. Appends are fire-and-
 *-forget: a failing audit write must never block (or silently fake) a payment,
 * so the failure is logged and the caller still gets its result.
 *
 * ## On `PaymentRecord.reference`
 *
 * The schema comments it as "our reference, generated by us". For a gateway
 * that is right — we must hand the reference to the gateway. For a manual bank
 * transfer the ONLY reference that exists is the bank's, and it is the one
 * that must be unique: the same transfer must not be entered twice by two
 * operators. So here `reference` is the operator-supplied bank reference and it
 * is the dedupe key. Dual control is the second line of defence behind it.
 */

import { db } from "@/lib/db";
import { append as auditAppend } from "@/lib/audit-chain";
import { logError } from "@/lib/validation/safe-log";
import {
  assertMoney,
  decodeEntitlements,
  encodeEntitlements,
  settlePayment,
  type Money,
  type PaymentProvider,
  type RefundRequest,
  type RefundResult,
  type StoredEntitlement,
  type StoredAuthorization,
  type CheckoutRequest,
  type CheckoutSession,
  type WebhookVerification,
} from "@/lib/payments/provider";

export const MANUAL_INVOICE_PROVIDER_ID = "manualinvoice";

export type RecordPaymentInput = {
  orgId: string;
  /** The bank transfer reference, exactly as it appears on the statement. */
  bankReference: string;
  money: Money;
  /** Better Auth user id of the operator entering the payment. */
  recordedBy: string;
  entitlements?: StoredEntitlement[];
  purpose?: string;
  note?: string;
};

export type RecordPaymentResult =
  | { ok: true; reference: string; paymentId: string; duplicate: boolean }
  | { ok: false; reason: "invalid_reference" | "invalid_recorder"; detail?: string };

/**
 * Step 1 of 2. Records that a payment is *claimed*. Credits nothing.
 *
 * Idempotent on the bank reference: a second operator entering the same
 * transfer gets `{ duplicate: true }` and NO second row, so a double-typed
 * transfer cannot be counted twice before dual control even comes into play.
 */
export async function recordPayment(input: RecordPaymentInput): Promise<RecordPaymentResult> {
  const money = assertMoney(input.money, "recordPayment.money");
  const reference = sanitizeReference(input.bankReference);
  if (!reference) return { ok: false, reason: "invalid_reference" };
  const recordedBy = sanitizeActor(input.recordedBy);
  if (!recordedBy) return { ok: false, reason: "invalid_recorder" };

  const envelope = encodeEntitlements({
    version: 1,
    entitlements: input.entitlements ?? [],
    recordedBy,
    ...(input.purpose === undefined ? {} : { purpose: input.purpose }),
    ...(input.note === undefined ? {} : { note: input.note }),
  });

  const paymentId = `mi_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 12)}`;
  const inserted = await db.$queryRaw<{ id: string }[]>`
    INSERT INTO "PaymentRecord"
      ("id", "orgId", "provider", "reference", "amountMinor", "currency", "status",
       "entitlementsJson", "createdAt")
    VALUES (${paymentId}, ${input.orgId}, ${MANUAL_INVOICE_PROVIDER_ID}, ${reference},
            ${money.amountMinor}, ${money.currency}, 'pending', ${envelope}, ${new Date()})
    ON CONFLICT ("reference") DO NOTHING
    RETURNING "id"
  `;
  const duplicate = inserted.length === 0;
  // Not a duplicate means `inserted.length !== 0`, i.e. the INSERT's
  // `RETURNING "id"` produced at least this row, so `inserted[0]` is populated.
  const id = duplicate
    ? ((await db.paymentRecord.findUnique({ where: { reference }, select: { id: true } }))?.id ??
      "")
    : inserted[0]!.id;

  await auditPayment({
    reference,
    orgId: input.orgId,
    actor: recordedBy,
    intent: duplicate ? "payment_record_duplicate" : "payment_recorded",
    detail: `${money.amountMinor} ${money.currency}`,
    meta: {
      amountMinor: money.amountMinor,
      currency: money.currency,
      provider: MANUAL_INVOICE_PROVIDER_ID,
      duplicate,
    },
  });

  return { ok: true, reference, paymentId: id, duplicate };
}

export type VerifyPaymentInput = {
  /** The bank transfer reference being verified. */
  bankReference: string;
  /** Better Auth user id of the operator confirming arrival. Must differ from the recorder. */
  verifiedBy: string;
  note?: string;
};

export type VerifyPaymentResult =
  | {
      ok: true;
      reference: string;
      paymentId: string;
      unitsCredited: number;
      alreadyVerified: boolean;
    }
  | {
      ok: false;
      reason:
        | "not_found"
        | "already_failed"
        | "self_verification_forbidden"
        | "missing_recorder"
        | "invalid_actor";
      detail?: string;
    };

/**
 * Step 2 of 2. Dual control: the verifier must be a DIFFERENT operator from the
 * one who recorded it. Grants the entitlement and credits the units.
 *
 * Rejecting `verifiedBy === recordedBy` is the entire point of this adapter, so
 * the check is done against the persisted recorder, not an argument.
 */
export async function verifyPayment(input: VerifyPaymentInput): Promise<VerifyPaymentResult> {
  const reference = sanitizeReference(input.bankReference);
  const verifiedBy = sanitizeActor(input.verifiedBy);
  if (!verifiedBy) return { ok: false, reason: "invalid_actor" };
  if (!reference) return { ok: false, reason: "not_found" };

  const row = await db.paymentRecord.findUnique({ where: { reference } });
  if (!row) return { ok: false, reason: "not_found" };
  if (row.status === "failed") return { ok: false, reason: "already_failed" };
  if (row.status === "success" || row.status === "refunded") {
    return { ok: true, reference, paymentId: row.id, unitsCredited: 0, alreadyVerified: true };
  }

  const envelope = decodeEntitlements(row.entitlementsJson);
  const recordedBy = envelope.recordedBy;
  if (!recordedBy) {
    // A row without a recorder cannot satisfy dual control. Fail closed.
    return { ok: false, reason: "missing_recorder" };
  }
  if (recordedBy === verifiedBy) {
    await auditPayment({
      reference,
      orgId: row.orgId ?? undefined,
      actor: verifiedBy,
      intent: "payment_selfverify_blocked",
      detail: "dual control: recorder may not verify",
      meta: { provider: MANUAL_INVOICE_PROVIDER_ID },
    });
    return { ok: false, reason: "self_verification_forbidden", detail: recordedBy };
  }
  if (!row.orgId) {
    // A payment with no organisation cannot be credited to a ledger. Fail
    // closed rather than settling a payment whose units go nowhere.
    return { ok: false, reason: "not_found", detail: "payment has no orgId" };
  }

  // settlePayment owns the `pending -> success` transition, and does it with a
  // single conditional UPDATE, so two verifiers racing on this row cannot both
  // settle it. Do NOT pre-flip the row here: that would make settlePayment's
  // unique insert always conflict and silently credit nothing.
  const settle = await settlePayment({
    provider: MANUAL_INVOICE_PROVIDER_ID,
    orgId: row.orgId,
    reference,
    money: { amountMinor: row.amountMinor, currency: row.currency },
    status: "success",
    eventId: `manual:${reference}`,
    entitlements: envelope.entitlements,
    purpose: envelope.purpose,
    note: input.note ?? envelope.note,
    verifiedBy,
    recordedBy,
  });

  if (!settle.applied) {
    return {
      ok: true,
      reference,
      paymentId: settle.paymentId,
      unitsCredited: 0,
      alreadyVerified: true,
    };
  }

  await auditPayment({
    reference,
    orgId: row.orgId ?? undefined,
    actor: verifiedBy,
    intent: settle.applied ? "payment_verified" : "payment_verified_duplicate",
    detail: `${row.amountMinor} ${row.currency}`,
    meta: {
      amountMinor: row.amountMinor,
      currency: row.currency,
      recordedBy,
      verifiedBy,
      unitsCredited: settle.unitsCredited,
      provider: MANUAL_INVOICE_PROVIDER_ID,
    },
  });

  return {
    ok: true,
    reference,
    paymentId: settle.paymentId,
    unitsCredited: settle.unitsCredited,
    alreadyVerified: false,
  };
}

/**
 * The audit chain is the evidence of record for every money movement. Appends
 * are `fast` (no $transaction of their own) and fire-and-forget: an audit
 * outage must not block a bank transfer, but it must be visible.
 */
async function auditPayment(input: {
  reference: string;
  orgId?: string;
  actor: string;
  intent: string;
  detail: string;
  meta: Record<string, unknown>;
}): Promise<void> {
  await auditAppend(
    {
      callRef: `PAY-${input.reference}`,
      action: "consent",
      intent: input.intent,
      callerId: input.actor,
      redactedText: input.detail.slice(0, 500),
      meta: input.meta,
      ...(input.orgId === undefined ? {} : { orgId: input.orgId }),
    },
    { fast: true },
  ).catch((err: unknown) => {
    logError("[manual-invoice] payment audit append failed", {
      error: err instanceof Error ? err.message : String(err),
    });
  });
}

const REF_RE = /^[A-Za-z0-9._:\-/]{4,64}$/;

function sanitizeReference(raw: string | undefined): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  return REF_RE.test(trimmed) ? trimmed : null;
}

function sanitizeActor(raw: string | undefined): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw
    .trim()
    .replace(/[^\w.:-]/g, "")
    .slice(0, 64);
  return trimmed === "" ? null : trimmed;
}

// ── the port implementation ───────────────────────────────────────────────────

/**
 * A bank transfer has no hosted checkout, no signed callback and no stored card
 * authorization. Every one of those port methods returns an explicit typed
 * refusal instead of a plausible-looking fake — a ManualInvoice adapter that
 * fabricated a checkout URL would be worse than one that admits it has none.
 */
export function createManualInvoiceProvider(): PaymentProvider {
  return {
    id: MANUAL_INVOICE_PROVIDER_ID,

    async createCheckout(_req: CheckoutRequest): Promise<CheckoutSession> {
      throw new Error(
        "manualinvoice: bank transfers are started by issuing a quote, not a checkout URL",
      );
    },

    async verifyWebhook(_input: {
      rawBody: Buffer | string;
      headers: Record<string, string | string[] | undefined>;
    }): Promise<WebhookVerification> {
      return {
        ok: false,
        reason: "unsupported_event",
        detail: "manualinvoice has no webhook surface",
      };
    },

    async chargeStoredAuthorization(_req: {
      orgId: string;
      authorization: StoredAuthorization;
      money: Money;
      purpose: string;
      requestKey: string;
    }): Promise<
      | { ok: true; reference: string; verified: true }
      | { ok: false; reference: string; reason: string }
    > {
      return {
        ok: false,
        reference: "",
        reason: "manualinvoice: overage must be invoiced and verified manually",
      };
    },

    async listEntitlements(reference: string): Promise<StoredEntitlement[]> {
      const row = await db.paymentRecord.findUnique({
        where: { reference },
        select: { entitlementsJson: true },
      });
      return decodeEntitlements(row?.entitlementsJson).entitlements;
    },

    async refund(req: RefundRequest): Promise<RefundResult> {
      const existing = await db.paymentRecord.findUnique({
        where: { reference: req.reference },
        select: { id: true, status: true },
      });
      if (!existing) return { ok: false, reference: req.reference, reason: "not_found" };
      if (existing.status === "refunded") {
        return { ok: false, reference: req.reference, reason: "already_refunded" };
      }
      await db.paymentRecord.update({ where: { id: existing.id }, data: { status: "refunded" } });
      return { ok: true, reference: req.reference };
    },
  };
}
