import "server-only";
/**
 * Paddle adapter — implements the `PaymentProvider` port from `./provider`.
 *
 * Everything Paddle-shaped stops at this file. The only things that cross the
 * boundary are port types. A caller must never be able to tell which gateway is
 * behind a checkout.
 *
 * ## Four rules this implementation exists to enforce
 *
 *   1. **HMAC-SHA256 over `ts + ":" + the RAW BYTES`, from a caller-supplied
 *      timestamp.** Paddle signs `` `${ts}:${rawBody}` `` where `ts` is the value
 *      in the signature header itself, not `Date.now()`. Two classic bugs are
 *      structurally impossible here and each is covered by a negative test:
 *        - signing over the body alone (the `ts:` prefix dropped);
 *        - `JSON.parse` then `JSON.stringify` before hashing — a re-serialised
 *      body changes key order and whitespace and MUST be rejected. So
 *      `verifyWebhook` takes a `Buffer` and never re-serialises.
 *      A stale `ts` is refused on its own tolerance window, which is what stops
 *      a captured-and-replayed webhook from settling twice.
 *   2. **A webhook is a CLAIM, not a fact.** `verifyWebhook` proves the bytes
 *      came from Paddle. It does not prove the money moved. Settlement is
 *      `settlePayment`'s job and is guarded by its own idempotency.
 *   3. **Our reference is generated by us**, never accepted from a client, and
 *      it rides to Paddle in `custom_data` so the webhook can hand it back.
 *   4. **Checkout is PRICE-DRIVEN, which is the hard impedance mismatch here.**
 *      The port's `CheckoutRequest` carries a `Money` (an amount); Paddle will
 *      only accept a `priceId` it already knows. So this adapter needs a price
 *      catalog, and a request whose amount matches no configured price is
 *      REFUSED with a loud error naming the missing key — never silently charged
 *      to a neighbouring tier. Getting that wrong bills a customer for the plan
 *      they did not choose, which is not a bug you find in staging.
 *
 * ## `chargeStoredAuthorization` is NOT SUPPORTED, and that is deliberate
 *
 * The port member exists to charge computed overage against a card authorization
 * captured earlier. Paddle is a Merchant of Record: there is no stored card
 * authorization, no vault, and no way to take a payment later against a prior
 * consent. This is a gap in Paddle's product, not in this implementation.
 *
 * So the method returns a refusal naming the reason rather than pretending. The
 * alternative — implementing it with a subscription and a usage meter — would be
 * a different billing model wearing this one's interface, and `overage.ts` would
 * need rewriting rather than just re-pointing. Fail loudly; decide deliberately.
 *
 * ## MoR changes what `amountMinor` means
 *
 * Paddle collects and remits sales tax, so a transaction's `unit_price` is
 * gross-of-tax in the *currency the buyer is charged in*, which may not be the
 * currency we priced in. Anything that assumes "charged == received" has to be
 * re-examined. `credits` are denominated in minor units in `provider.ts`, so a
 * customer buying GBP is credited GBP-minor units unless that is handled
 * upstream — see the `paddleCurrency` note on `createCheckout`.
 *
 * ## Sandbox guard
 *
 * The default key must start with `pdl_sdbx_`. A live key is refused unless
 * `PADDLE_ALLOW_LIVE_KEYS=1` is set explicitly, so this adapter cannot reach a
 * live gateway by accident — the same posture `paystack.ts` takes.
 *
 * ## No live network in tests
 *
 * The HTTP client is injected; every gate supplies a mock. `createPaddleProvider`
 * is the only construction path, so there is no global client to accidentally hit
 * the network from.
 */

import { createHmac, timingSafeEqual } from "node:crypto";
import {
  assertMoney,
  entitlementsFor,
  type ChargeRequest,
  type ChargeResult,
  type CheckoutRequest,
  type CheckoutSession,
  type PaymentProvider,
  type ProviderEvent,
  type RefundRequest,
  type RefundResult,
  type StoredEntitlement,
  type WebhookVerification,
} from "@/lib/payments/provider";

export const PADDLE_PROVIDER_ID = "paddle";
export const PADDLE_SIGNATURE_HEADER = "paddle-signature";
export const PADDLE_ALLOW_LIVE_ENV = "PADDLE_ALLOW_LIVE_KEYS";
export const SECRET_KEY_ENV = "PADDLE_API_KEY";
export const WEBHOOK_SECRET_ENV = "PADDLE_WEBHOOK_SECRET";
export const PRICES_ENV = "PADDLE_PRICES";

/** Replay window. Paddle's own dashboard default is 5 minutes. */
export const SIGNATURE_TOLERANCE_SEC = Number(process.env.PADDLE_SIGNATURE_TOLERANCE_SEC) || 300;

function defaultBaseUrl(): string {
  return process.env.PADDLE_BASE_URL ?? "https://sandbox-api.paddle.com";
}

// ── signature ─────────────────────────────────────────────────────────────────

/**
 * The `Paddle-Signature` header: `ts=<unix seconds>;h1=<hex hmac>`.
 *
 * Parsed rather than pattern-matched into the caller's code, because a malformed
 * header and a wrong digest are DIFFERENT failures and the port models them as
 * different reasons (`malformed_signature` vs `digest_mismatch`) — a caller
 * triaging a webhook queue needs to tell "someone sent us junk" apart from
 * "someone tampered with a real event".
 */
export type PaddleSignature = { ts: string; h1: string };

export function parseSignatureHeader(header: string): PaddleSignature | null {
  for (const part of header.split(";")) {
    const eq = part.indexOf("=");
    if (eq <= 0) continue;
    const key = part.slice(0, eq).trim();
    const value = part.slice(eq + 1).trim();
    if (key === "ts" && value !== "") return parseH1(header);
  }
  return null;
}

function parseH1(header: string): PaddleSignature | null {
  let ts = "";
  let h1 = "";
  for (const part of header.split(";")) {
    const eq = part.indexOf("=");
    if (eq <= 0) continue;
    const key = part.slice(0, eq).trim();
    const value = part.slice(eq + 1).trim();
    if (key === "ts") ts = value;
    else if (key === "h1") h1 = value;
  }
  if (ts === "" || h1 === "") return null;
  if (!/^\d+$/.test(ts)) return null;
  if (!/^[0-9a-fA-F]+$/.test(h1) || h1.length % 2 !== 0) return null;
  return { ts, h1: h1.toLowerCase() };
}

/**
 * `HMAC-SHA256(`${ts}:${rawBody}`, secret)` as lowercase hex, over the RAW
 * bytes. The `ts:` prefix is Paddle's and dropping it produces a digest that is
 * always wrong — which is the safe direction, but it must be right for the right
 * reason, so it is asserted directly rather than left to fall out of a passing
 * fixture.
 */
export function paddleDigest(rawBody: Buffer | string, secret: string, ts: string): string {
  const body = Buffer.isBuffer(rawBody) ? rawBody : Buffer.from(rawBody, "utf8");
  return createHmac("sha256", secret).update(`${ts}:`).update(body).digest("hex");
}

/** Constant-time compare, with the length check FIRST — `timingSafeEqual` throws on mismatch. */
export function digestMatches(expected: string, presented: string): boolean {
  const a = Buffer.from(expected, "hex");
  let b: Buffer;
  try {
    b = Buffer.from(presented, "hex");
  } catch {
    return false;
  }
  if (a.length === 0 || a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/** Reject a replayed event. `now` is injected so this costs no wall-clock in tests. */
export function timestampFresh(ts: string, now: number = Date.now()): boolean {
  const seconds = Number(ts);
  if (!Number.isFinite(seconds)) return false;
  return Math.abs(now / 1000 - seconds) <= SIGNATURE_TOLERANCE_SEC;
}

// ── reference ─────────────────────────────────────────────────────────────────

/** Crockford base32 — same alphabet as the Paystack adapter's ULID. */
const ULID_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/** Monotonic ULID: 48-bit ms timestamp + 80 bits of randomness. */
export function ulid(now: number = Date.now()): string {
  let time = "";
  let t = now;
  for (let i = 0; i < 10; i++) {
    time = ULID_ALPHABET[t % 32] + time;
    t = Math.floor(t / 32);
  }
  const buf = new Uint8Array(16);
  for (let i = 0; i < 16; i++) buf[i] = Math.floor(Math.random() * 256);
  let random = "";
  for (const byte of buf) random = ULID_ALPHABET[byte % 32] + random;
  return (time + random).slice(0, 26);
}

function sanitizeSegment(value: string, max: number): string {
  return value.replace(/[^A-Za-z0-9_-]/g, "").slice(0, max);
}

/** `org_{orgId}_{purpose}_{ulid}` — ours, never accepted from a client. */
export function buildReference(orgId: string, purpose: string): string {
  const org = sanitizeSegment(orgId, 40);
  const why = sanitizeSegment(purpose, 24) || "topup";
  if (org === "") throw new TypeError("orgId is required to build a payment reference");
  return `org_${org}_${why}_${ulid()}`;
}

export function parseReference(reference: string): { orgId: string; purpose: string } | null {
  const m = /^org_([A-Za-z0-9_-]{1,40})_([A-Za-z0-9_-]{1,24})_[0-9A-Z]{26}$/.exec(reference);
  if (!m) return null;
  return { orgId: m[1]!, purpose: m[2]! };
}

// ── price catalog ─────────────────────────────────────────────────────────────

/**
 * Canonical key for a configured price: `<currency>_<minor>_<interval>`.
 *
 * `interval` is `month`, `year` or `once`. Lower-case currency, integer minor
 * units — the two things Paddle itself treats as significant, and the two that
 * make a typo fail loudly instead of resolving to a real, wrong price.
 */
export function priceKey(
  money: { amountMinor: number; currency: string },
  interval: "month" | "year" | "once",
): string {
  return `${money.currency.toLowerCase()}_${money.amountMinor}_${interval}`;
}

export type PaddlePriceMap = Record<string, string>;

/**
 * Read the price map from `PADDLE_PRICES`.
 *
 * A JSON object rather than one env var per tier: twenty-odd vars is a config
 * surface nobody can review, and the whole point of the map is that the amount
 * and the `pri_` id are checked against each other in one place.
 */
export function parsePriceMap(raw: string | undefined): PaddlePriceMap {
  if (!raw || raw.trim() === "") return {};
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new TypeError(`${PRICES_ENV} is not valid JSON`);
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new TypeError(`${PRICES_ENV} must be a JSON object of priceKey -> pri_...`);
  }
  const out: PaddlePriceMap = {};
  for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
    if (typeof v !== "string" || !/^pri_[A-Za-z0-9]+$/.test(v)) {
      throw new TypeError(`${PRICES_ENV}["${k}"] must be a Paddle price id (pri_...)`);
    }
    out[k] = v;
  }
  return out;
}

// ── event decoding ────────────────────────────────────────────────────────────

/**
 * Map a verified Paddle event onto the port's `ProviderEvent`.
 *
 * Only the events that correspond to a `kind` the port models are accepted;
 * everything else returns null and surfaces as `unsupported_event` rather than
 * being decoded into a guess. `subscription.*` events are deliberately NOT
 * mapped: the port's `kind` is about money, and a subscription state change is
 * not a charge. Mapping one onto the other would credit a wallet on a plan
 * change.
 */
export function decodePaddleEvent(payload: Record<string, unknown>): ProviderEvent | null {
  const eventId = typeof payload.event_id === "string" ? payload.event_id : "";
  const eventType = typeof payload.event_type === "string" ? payload.event_type : "";
  if (eventId === "" || eventType === "") return null;

  const data = payload.data;
  if (!data || typeof data !== "object") return null;
  const d = data as Record<string, unknown>;

  const custom = d.custom_data;
  const reference =
    custom && typeof custom === "object" && typeof (custom as { reference?: unknown }).reference === "string"
      ? (custom as { reference: string }).reference
      : "";
  // A reference we did not mint is not ours to settle. Without this a Paddle
  // event carrying someone else's `custom_data` would be credited to an org.
  if (reference === "" || parseReference(reference) === null) return null;

  const items = Array.isArray(d.items) ? (d.items as Record<string, unknown>[]) : [];
  const first = items[0];
  if (!first) return null;
  const unit = first.unit_price as { amount?: unknown; currency_code?: unknown } | undefined;
  const amountMinor = Number(unit?.amount);
  const currency = typeof unit?.currency_code === "string" ? unit.currency_code : "";
  if (!Number.isInteger(amountMinor) || amountMinor <= 0 || !/^[A-Za-z]{3}$/.test(currency)) {
    return null;
  }

  const occurredAt =
    typeof d.occurred_at === "string"
      ? d.occurred_at
      : typeof d.completed_at === "string"
        ? d.completed_at
        : new Date().toISOString();

  let kind: ProviderEvent["kind"];
  if (eventType === "transaction.completed") kind = "charge.succeeded";
  else if (eventType === "transaction.failed") kind = "charge.failed";
  else if (eventType === "transaction.refunded") kind = "refund.succeeded";
  else return null;

  return {
    eventId,
    kind,
    reference,
    money: { amountMinor, currency: currency.toUpperCase() },
    occurredAt,
    metadata: {
      paddleTransactionId: typeof d.id === "string" ? d.id : "",
      eventType,
      status: typeof d.status === "string" ? d.status : "",
    },
  };
}

// ── HTTP ──────────────────────────────────────────────────────────────────────

export type HttpClient = (url: string, init: RequestInit) => Promise<Response>;

export type PaddleConfig = {
  apiKey: string;
  webhookSecret: string;
  prices: PaddlePriceMap;
  baseUrl?: string;
  /**
   * Injected in every gate. Defaults to `globalThis.fetch` inside
   * `normalizeConfig`, so a production call site does not have to write it.
   */
  http?: HttpClient;
};

function normalizeConfig(cfg: PaddleConfig): Required<Omit<PaddleConfig, "apiKey" | "webhookSecret">> & {
  apiKey: string;
  webhookSecret: string;
  prices: PaddlePriceMap;
} {
  const apiKey = cfg.apiKey?.trim() ?? "";
  if (apiKey === "") throw new TypeError(`${SECRET_KEY_ENV} is required`);

  const live = apiKey.startsWith("pdl_live_");
  const sandbox = apiKey.startsWith("pdl_sdbx_");
  if (!live && !sandbox) {
    throw new TypeError(
      `${SECRET_KEY_ENV} does not look like a Paddle key (expected a "pdl_sdbx_" or "pdl_live_" prefix)`,
    );
  }
  if (live && process.env[PADDLE_ALLOW_LIVE_ENV] !== "1") {
    throw new TypeError(
      `refusing a LIVE Paddle key: set ${PADDLE_ALLOW_LIVE_ENV}=1 to allow it deliberately. ` +
        `This guard exists so a mis-set environment cannot take real money.`,
    );
  }

  const webhookSecret = cfg.webhookSecret?.trim() ?? "";
  if (webhookSecret === "") throw new TypeError(`${WEBHOOK_SECRET_ENV} is required`);

  return {
    apiKey,
    webhookSecret,
    prices: cfg.prices ?? {},
    baseUrl: cfg.baseUrl ?? defaultBaseUrl(),
    http: cfg.http ?? ((url, init) => fetch(url, init)),
  };
}

type Resolved = ReturnType<typeof normalizeConfig>;

async function paddleRequest<T>(
  cfg: Resolved,
  method: "GET" | "POST",
  path: string,
  body?: unknown,
): Promise<{ ok: true; value: T } | { ok: false; error: string }> {
  let res: Response;
  try {
    res = await cfg.http(`${cfg.baseUrl}${path}`, {
      method,
      headers: {
        // Paddle authenticates with the API key as the Basic-auth USERNAME and
        // an EMPTY password — not as a bearer token. This was the reason a
        // hand-rolled `Authorization: Basic <key>` probe 403'd while the SDK
        // worked: the SDK sends the same scheme, and anything else does not.
        Authorization: `Basic ${Buffer.from(`${cfg.apiKey}:`).toString("base64")}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
  } catch (e) {
    return { ok: false, error: `network_error:${e instanceof Error ? e.message : "unknown"}` };
  }

  const text = await res.text().catch(() => "");
  if (!res.ok) {
    // Paddle's error envelope is `{ code, message }`. Surfacing the code matters:
    // 401 means the key, 403 means permissions on that resource, and they have
    // completely different fixes.
    let detail = `http_${res.status}`;
    try {
      const parsed = JSON.parse(text) as { code?: string; message?: string };
      if (parsed?.code) detail = `http_${res.status}:${parsed.code}`;
    } catch {
      /* non-JSON error body — the status alone is the signal */
    }
    return { ok: false, error: detail };
  }
  if (text === "") return { ok: true, value: {} as T };
  try {
    return { ok: true, value: JSON.parse(text) as T };
  } catch {
    return { ok: false, error: "malformed_response" };
  }
}

function headerValue(
  headers: Record<string, string | string[] | undefined>,
  name: string,
): string | undefined {
  const v = headers[name] ?? headers[name.toLowerCase()];
  if (Array.isArray(v)) return v[0];
  return v ?? undefined;
}

// ── provider ──────────────────────────────────────────────────────────────────

type TransactionResponse = {
  data?: {
    id?: string;
    checkout?: { url?: string };
    custom_data?: { reference?: string };
  };
};

export function createPaddleProvider(cfg: PaddleConfig): PaymentProvider {
  const c = normalizeConfig(cfg);

  /**
   * `POST /transactions` — Paddle's hosted checkout.
   *
   * `collectionMode: "automatic"` means Paddle charges the saved/default method
   * without a further confirmation step, which is what makes the webhook the
   * only settlement signal we have. "manual" would require an explicit capture
   * call this adapter deliberately does not make.
   */
  async function createCheckout(req: CheckoutRequest): Promise<CheckoutSession> {
    const money = assertMoney(req.money, "checkout.money");
    const reference = buildReference(req.orgId, req.purpose);

    // Which configured price is this amount? Refuse loudly rather than guess:
    // falling through to "the first price that fits" would bill a customer for
    // a tier they did not pick.
    const candidates: ("month" | "year")[] = ["month", "year"];
    const matches = candidates
      .map((interval) => {
        const key = priceKey(money, interval);
        const priceId = c.prices[key];
        return priceId ? { interval, priceId, key } : null;
      })
      .filter((m): m is { interval: "month" | "year"; priceId: string; key: string } => m !== null);

    if (matches.length === 0) {
      const wanted = candidates.map((i) => priceKey(money, i)).join(" or ");
      throw new Error(
        `paddle: no configured price matches this checkout (looked for "${wanted}"). ` +
          `Add it to ${PRICES_ENV}. Refusing to guess — charging a neighbouring tier is ` +
          `worse than failing.`,
      );
    }
    // Ambiguous if the same amount is configured for both intervals. Prefer
    // monthly (the common case) and say so, because silently picking yearly
    // would charge 10x for the same request.
    const chosen = matches.find((m) => m.interval === "month") ?? matches[0]!;

    const res = await paddleRequest<TransactionResponse>(
      c,
      "POST",
      "/transactions",
      {
        items: [{ price_id: chosen.priceId, quantity: 1 }],
        collection_mode: "automatic",
        custom_data: { reference },
        customer: { email: req.email },
        ...(req.returnUrl === undefined ? {} : { settings: { return_url: req.returnUrl } }),
      },
    );
    if (!res.ok) throw new Error(`paddle: checkout failed (${res.error})`);

    const url = res.value.data?.checkout?.url ?? "";
    if (url === "") throw new Error("paddle: transaction created but no checkout url returned");
    // Paddle has no `access_code` concept; the field exists on the port for
    // Paystack's benefit. Empty is honest, and callers that need a token must
    // use `reference`, which is ours and stable.
    return { url, accessCode: "", reference };
  }

  return {
    id: PADDLE_PROVIDER_ID,

    createCheckout,

    /**
     * Paddle signs `ts:rawBody` with the notification-destination secret. Does
     * NOT settle — `settlePayment` is the only writer of a successful payment.
     */
    async verifyWebhook(input: {
      rawBody: Buffer | string;
      headers: Record<string, string | string[] | undefined>;
    }): Promise<WebhookVerification> {
      const header = headerValue(input.headers, PADDLE_SIGNATURE_HEADER);
      if (!header) return { ok: false, reason: "missing_signature" };

      const parsed = parseSignatureHeader(header);
      if (!parsed) return { ok: false, reason: "malformed_signature" };

      // Replay guard FIRST. A captured webhook replayed inside the window still
      // verifies, so the tolerance is the only thing bounding the replay attack;
      // beyond it we refuse before spending a HMAC.
      if (!timestampFresh(parsed.ts)) return { ok: false, reason: "digest_mismatch" };

      const expected = paddleDigest(input.rawBody, c.webhookSecret, parsed.ts);
      if (!digestMatches(expected, parsed.h1)) {
        return { ok: false, reason: "digest_mismatch" };
      }

      let payload: Record<string, unknown>;
      try {
        const text = Buffer.isBuffer(input.rawBody)
          ? input.rawBody.toString("utf8")
          : input.rawBody;
        const parsedBody = JSON.parse(text) as unknown;
        if (!parsedBody || typeof parsedBody !== "object") {
          return { ok: false, reason: "malformed_body" };
        }
        payload = parsedBody as Record<string, unknown>;
      } catch {
        return { ok: false, reason: "malformed_body" };
      }

      const event = decodePaddleEvent(payload);
      if (!event) return { ok: false, reason: "unsupported_event" };
      return { ok: true, event };
    },

    /**
     * NOT SUPPORTED — see the file header. Paddle is a Merchant of Record and
     * exposes no stored card authorization to charge later.
     *
     * Returns a refusal rather than throwing, because the port's contract is
     * `ChargeResult` and a caller that can handle `ok: false` (retry, fall back
     * to a fresh checkout, degrade) should not have to catch. `overage.ts` must
     * check this rather than assume it worked.
     */
    async chargeStoredAuthorization(req: ChargeRequest): Promise<ChargeResult> {
      const reference = buildReference(req.orgId, req.purpose);
      return {
        ok: false,
        reference,
        reason: "stored_authorization_unsupported_by_paddle",
      };
    },

    listEntitlements(reference: string): Promise<StoredEntitlement[]> {
      return entitlementsFor(reference);
    },

    /**
     * Paddle refunds against the ORIGINAL transaction, so it needs the Paddle
     * transaction id — which is not in our `reference` and cannot be added to
     * `RefundRequest` without moving a port contract this file does not own.
     *
     * So it is read back from where settlement already put it: the entitlement
     * envelope on the `PaymentRecord`. The webhook event carries
     * `metadata.paddleTransactionId`; the settling route stores it on an
     * entitlement; `entitlementsFor` reads it here. That keeps the id, the
     * PaymentRecord and the audit envelope consistent with one another instead
     * of inventing a side table that can drift from them.
     *
     * A missing id is a REFUSAL, never a silent no-op: an operator told
     * "refund failed" can retry; an operator told "refunded" who was not cannot.
     */
    async refund(req: RefundRequest): Promise<RefundResult> {
      // Validated for its throw on malformed money even though the amount itself
      // is unused here — Paddle refunds the original transaction, it does not
      // take an amount.
      assertMoney(req.money, "refund.money");

      const transactionId = await paddleTransactionIdFor(req.reference);
      if (transactionId === "") {
        return { ok: false, reference: req.reference, reason: "missing_paddle_transaction_id" };
      }

      const res = await paddleRequest(c, "POST", "/transactions", {
        action: "refund",
        transaction_id: transactionId,
        ...(req.reason === undefined ? {} : { reason: req.reason.slice(0, 200) }),
      });
      if (!res.ok) return { ok: false, reference: req.reference, reason: res.error };

      // Deliberately does NOT call `refundPayment`. Writing PaymentRecord /
      // ledger state is the settling route's job — it owns the dual-control
      // evidence — and an adapter doing it here would be a second writer.
      return { ok: true, reference: req.reference };
    },
  };
}

/**
 * The Paddle transaction id recorded at settlement time.
 *
 * Returns "" when the reference is unknown or was settled without one — both of
 * which are legitimate states, and both of which must produce a refusal rather
 * than an exception, because this runs on an operator-facing refund path.
 */
export async function paddleTransactionIdFor(reference: string): Promise<string> {
  let entitlements: StoredEntitlement[];
  try {
    entitlements = await entitlementsFor(reference);
  } catch {
    return "";
  }
  for (const e of entitlements) {
    const id = e.metadata?.["paddleTransactionId"];
    if (typeof id === "string" && id !== "") return id;
  }
  return "";
}