import "server-only";
/**
 * Paystack adapter (WP-13) — TEST KEYS ONLY.
 *
 * Everything Paystack-shaped stops at this file. The only things that cross the
 * boundary are the port types from `./provider`.
 *
 * ## Four rules the implementation exists to enforce
 *
 *   1. **HMAC-SHA512 over the RAW BYTES.** Paystack signs the exact request
 *      body with the secret key using SHA-512. Two classic bugs are structurally
 *      impossible here and are each covered by a negative test:
 *        - signing/verifying with **SHA-256** (`verifyWebhookDigest` takes the
 *          algorithm from nowhere but is only ever called with "sha512");
 *        - `JSON.parse` then `JSON.stringify` before hashing — a **re-serialised
 *          body** changes key order and whitespace and MUST be rejected. So
 *          `verifyWebhook` takes a `Buffer` and never re-serialises, and the
 *          raw-bytes check is asserted directly in the gate.
 *   2. **Never trust the browser callback.** `onCheckoutComplete` ignores
 *      whatever the redirect query string claims and re-verifies server-side
 *      with `GET /transaction/verify/{reference}`, acting only when
 *      `status === "success"` AND amount AND currency both match what we
 *      recorded. A tampered callback (`?status=success&amount=1`) buys nothing.
 *   3. **Our reference is generated by us**, shaped
 *      `org_{orgId}_{purpose}_{ulid}` — never accepted from the client, so a
 *      caller cannot collide two orgs onto one reference.
 *   4. **429 is retried with jittered backoff.** Paystack rate-limits; a
 *      webhook handler that treats 429 as a failure loses a real payment.
 *
 * ## No live network in tests
 *
 * The HTTP client is injected. The default is `globalThis.fetch`, but every
 * gate supplies a mock, and `createPaystackProvider` additionally refuses a
 * non-`sk_test_` secret key unless `PAYSTACK_ALLOW_LIVE_KEYS=1` is set
 * explicitly. The adapter therefore cannot reach a live gateway by accident.
 */

import { createHmac, timingSafeEqual } from "node:crypto";
import {
  assertMoney,
  entitlementsFor,
  refundPayment,
  settlePayment,
  type ChargeRequest,
  type ChargeResult,
  type CheckoutRequest,
  type CheckoutSession,
  type Money,
  type PaymentProvider,
  type ProviderEvent,
  type RefundRequest,
  type RefundResult,
  type StoredAuthorization,
  type StoredEntitlement,
  type WebhookVerification,
} from "@/lib/payments/provider";

export const PAYSTACK_PROVIDER_ID = "paystack";
export const PAYSTACK_SIGNATURE_HEADER = "x-paystack-signature";
export const PAYSTACK_ALLOW_LIVE_ENV = "PAYSTACK_ALLOW_LIVE_KEYS";
export const SECRET_KEY_ENV = "PAYSTACK_SECRET_KEY";

const DEFAULT_BASE_URL = "https://api.paystack.co";
/** Paystack rate limits aggressively; three attempts is the documented ceiling. */
const MAX_ATTEMPTS = 3;
const BASE_BACKOFF_MS = 250;
const REQUEST_TIMEOUT_MS = 10_000;

export type HttpClient = (url: string, init: RequestInit) => Promise<Response>;
export type Sleep = (ms: number) => Promise<void>;

export type PaystackConfig = {
  secretKey: string;
  baseUrl?: string;
  /** Injected in every gate. Defaults to `globalThis.fetch`. */
  http: HttpClient;
  /** Injected so the 429 retry ladder costs no wall-clock in tests. */
  sleep?: Sleep;
  /** Injected so jitter is deterministic under test. */
  rand?: () => number;
};

export type PaystackErrorBody = { status: boolean; message?: string };

// ── signature ─────────────────────────────────────────────────────────────────

/**
 * Paystack's signature: `HMAC-SHA512(rawBody, secretKey)` as lowercase hex,
 * compared in constant time. The digest is over the RAW bytes — a body that
 * has been parsed and re-stringified produces a different digest and is
 * rejected, which is the entire point.
 */
export function paystackDigest(rawBody: Buffer | string, secretKey: string): string {
  return createHmac("sha512", secretKey).update(rawBody).digest("hex");
}

/** True when every character is a hex digit. Anything else is not a signature. */
function isHex(value: string): boolean {
  return value.length % 2 === 0 && /^[0-9a-fA-F]+$/.test(value);
}

/** Constant-time comparison of a presented signature against the expected one. */
export function signatureMatches(expected: string, presented: string | undefined | null): boolean {
  if (typeof presented !== "string" || presented.length === 0) return false;
  const a = Buffer.from(expected, "hex");
  let b: Buffer;
  try {
    b = Buffer.from(presented.trim().toLowerCase(), "hex");
  } catch {
    return false;
  }
  // A wrong-length digest (notably SHA-256 where SHA-512 is required) is
  // rejected here. The check MUST come before the compare: timingSafeEqual
  // throws on length mismatch, and a length check is not a secret.
  if (a.length === 0 || a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

function headerValue(
  headers: Record<string, string | string[] | undefined>,
  name: string,
): string | undefined {
  const direct = headers[name] ?? headers[name.toLowerCase()] ?? headers[name.toUpperCase()];
  if (Array.isArray(direct)) return direct[0];
  return direct;
}

// ── reference generation ──────────────────────────────────────────────────────

const ULID_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"; // Crockford base32

/**
 * A monotonic ULID: 48-bit millisecond timestamp + 80 bits of randomness, in
 * Crockford base32. Implemented inline (13 lines) rather than pulled from a
 * dependency, because a reference is security-relevant and should not be able
 * to break on a transitive upgrade.
 */
export function ulid(now: number = Date.now()): string {
  let time = "";
  let t = now;
  for (let i = 0; i < 10; i++) {
    time = ULID_ALPHABET[t % 32] + time;
    t = Math.floor(t / 32);
  }
  let random = "";
  const buf = new Uint8Array(16);
  for (let i = 0; i < 16; i++) buf[i] = Math.floor(Math.random() * 256);
  // `buf` is a fixed 16-byte Uint8Array, so iterating it yields every byte
  // exactly once, in index order — the same sequence `buf[i]` produced, without
  // an index access TypeScript cannot prove in bounds.
  for (const byte of buf) {
    random = ULID_ALPHABET[byte % 32] + random;
  }
  return (time + random).slice(0, 26);
}

function sanitizeSegment(value: string, max: number): string {
  return value.replace(/[^A-Za-z0-9_-]/g, "").slice(0, max);
}

/** `org_{orgId}_{purpose}_{ulid}` — generated here, never accepted from a client. */
export function buildReference(orgId: string, purpose: string): string {
  const org = sanitizeSegment(orgId, 40);
  const why = sanitizeSegment(purpose, 24) || "topup";
  if (org === "") throw new TypeError("orgId is required to build a payment reference");
  return `org_${org}_${why}_${ulid()}`;
}

/** Recover `{orgId, purpose}` from one of our references. Null if not ours. */
export function parseReference(reference: string): { orgId: string; purpose: string } | null {
  const m = /^org_([A-Za-z0-9_-]{1,40})_([A-Za-z0-9_-]{1,24})_[0-9A-Z]{26}$/.exec(reference);
  if (!m) return null;
  // Both capture groups are mandatory in the pattern above — neither carries a
  // `?` quantifier and there is no top-level alternation — so a successful match
  // always populates `m[1]` and `m[2]`.
  return { orgId: m[1]!, purpose: m[2]! };
}

// ── HTTP ──────────────────────────────────────────────────────────────────────

/** Jittered exponential backoff: base * 2^n, ±25%, deterministic under test. */
export function backoffMs(attempt: number, rand: () => number = Math.random): number {
  const base = BASE_BACKOFF_MS * 2 ** Math.max(0, attempt - 1);
  const jitter = 0.75 + rand() * 0.5;
  return Math.round(base * jitter);
}

function isRetryable(status: number): boolean {
  // 429 is Paystack's documented rate-limit response; 408/5xx are transient.
  return status === 429 || status === 408 || (status >= 500 && status < 600);
}

type RawResponse = { status: number; body: unknown };

async function request(
  cfg: Required<PaystackConfig>,
  method: "GET" | "POST",
  path: string,
  body?: unknown,
): Promise<{ ok: true; value: RawResponse } | { ok: false; error: string }> {
  const sleep = cfg.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
  const url = `${cfg.baseUrl}${path}`;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    let res: Response;
    try {
      res = await cfg.http(url, {
        method,
        headers: {
          authorization: `Bearer ${cfg.secretKey}`,
          "content-type": "application/json",
          accept: "application/json",
        },
        ...(body === undefined ? {} : { body: JSON.stringify(body) }),
      });
    } catch (err) {
      if (attempt === MAX_ATTEMPTS)
        return { ok: false, error: `network_error: ${String(err).slice(0, 200)}` };
      await sleep(backoffMs(attempt, cfg.rand));
      continue;
    }

    if (isRetryable(res.status) && attempt < MAX_ATTEMPTS) {
      await sleep(backoffMs(attempt, cfg.rand));
      continue;
    }

    let parsed: unknown = null;
    const text = await res.text().catch(() => "");
    if (text) {
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
    }
    return { ok: true, value: { status: res.status, body: parsed } };
  }
  return { ok: false, error: "unreachable" };
}

/**
 * `request` for the paths where a transport failure is genuinely exceptional
 * (initialise, refund) — surfaced as a thrown Error. `verifyTransaction` uses
 * the `ok`/`error` shape instead, because a verify failure is an expected
 * outcome the caller has to handle, not a crash.
 */
async function requestOrThrow(
  cfg: NormalizedConfig,
  method: "GET" | "POST",
  path: string,
  body?: unknown,
): Promise<RawResponse> {
  const res = await request(cfg, method, path, body);
  if (!res.ok) throw new Error(res.error);
  return res.value;
}

type NormalizedConfig = {
  secretKey: string;
  baseUrl: string;
  http: HttpClient;
  sleep: Sleep;
  rand: () => number;
};

function requireOk(
  res: RawResponse,
  what: string,
): { ok: true; data: Record<string, unknown> } | { ok: false; error: string } {
  if (res.status < 200 || res.status >= 300) {
    const message = (res.body as PaystackErrorBody | null)?.message;
    return { ok: false, error: `${what} HTTP ${res.status}${message ? `: ${message}` : ""}` };
  }
  const data = res.body as Record<string, unknown> | null;
  if (!data || typeof data !== "object")
    return { ok: false, error: `${what}: malformed response body` };
  if (data.status === false) {
    return { ok: false, error: `${what}: ${String(data.message ?? "provider reported failure")}` };
  }
  return { ok: true, data };
}

function toInt(value: unknown): number | null {
  // Paystack returns numbers in JSON. A float or a non-numeric value is
  // rejected rather than rounded: money is never approximate here.
  if (typeof value !== "number" || !Number.isInteger(value)) return null;
  return Number.isSafeInteger(value) ? value : null;
}

function normalizeConfig(cfg: PaystackConfig): NormalizedConfig {
  if (!cfg.secretKey) throw new Error(`${SECRET_KEY_ENV} is not configured`);
  const allowLive = process.env[PAYSTACK_ALLOW_LIVE_ENV] === "1";
  if (!cfg.secretKey.startsWith("sk_test_") && !allowLive) {
    throw new Error(
      "paystack: refusing a non-test secret key. This adapter is test-keys-only; " +
        `set ${PAYSTACK_ALLOW_LIVE_ENV}=1 to override deliberately.`,
    );
  }
  return {
    secretKey: cfg.secretKey,
    baseUrl: (cfg.baseUrl ?? DEFAULT_BASE_URL).replace(/\/+$/, ""),
    http: cfg.http,
    sleep: cfg.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms))),
    rand: cfg.rand ?? Math.random,
  };
}

// ── the adapter ───────────────────────────────────────────────────────────────

export function createPaystackProvider(cfg: PaystackConfig): PaymentProvider {
  const c = normalizeConfig(cfg);

  /** `POST /transaction/initialize` — amount already in minor units. */
  async function initialize(req: CheckoutRequest): Promise<CheckoutSession> {
    const money = assertMoney(req.money, "checkout.money");
    // The reference is ours and deterministic per request key, so a retried
    // checkout reuses the reference Paystack already knows instead of creating
    // a second charge.
    const reference = buildReference(req.orgId, req.purpose);
    const res = await requestOrThrow(c, "POST", "/transaction/initialize", {
      email: req.email,
      amount: money.amountMinor,
      currency: money.currency,
      reference,
      ...(req.returnUrl === undefined ? {} : { callback_url: req.returnUrl }),
    });
    const ok = requireOk(res, "transaction/initialize");
    if (!ok.ok) throw new Error(ok.error);
    const data = ok.data.data as Record<string, unknown> | undefined;
    const url = typeof data?.authorization_url === "string" ? data.authorization_url : "";
    if (url === "") throw new Error("transaction/initialize: no authorization_url returned");
    return { url, accessCode: String(data?.access_code ?? ""), reference };
  }

  /**
   * `GET /transaction/verify/{reference}` — the server-side source of truth.
   * Called on the browser-return path precisely because the browser cannot be
   * trusted.
   */
  const verifyTransaction = (reference: string) => verifyTransactionServerSide(c, reference);

  /** `POST /transaction/charge_authorization` — computed overage on a stored auth. */
  async function chargeAuthorization(req: ChargeRequest): Promise<ChargeResult> {
    const money = assertMoney(req.money, "charge.money");
    if (!req.authorization?.authorizationCode) {
      return { ok: false, reference: "", reason: "missing_authorization_code" };
    }
    const reference = buildReference(req.orgId, req.purpose);
    const res = await requestOrThrow(c, "POST", "/transaction/charge_authorization", {
      email: req.authorization.email,
      authorization_code: req.authorization.authorizationCode,
      amount: money.amountMinor,
      currency: money.currency,
      reference,
    });
    const ok = requireOk(res, "transaction/charge_authorization");
    if (!ok.ok) return { ok: false, reference, reason: ok.error };

    // The gateway said the charge was accepted. That is a CLAIM: confirm it
    // server-side before reporting `verified: true`.
    const verified = await verifyTransaction(reference);
    if (!verified.ok) return { ok: false, reference, reason: verified.error };
    if (verified.status !== "success")
      return { ok: false, reference, reason: `status:${verified.status}` };
    if (
      verified.money.amountMinor !== money.amountMinor ||
      verified.money.currency !== money.currency
    ) {
      return { ok: false, reference, reason: "amount_or_currency_mismatch" };
    }
    return { ok: true, reference, verified: true };
  }

  return {
    id: PAYSTACK_PROVIDER_ID,

    createCheckout: initialize,

    /**
     * HMAC-SHA512 over the exact bytes received. Does not settle: the caller
     * must additionally confirm the transaction server-side.
     */
    async verifyWebhook(input: {
      rawBody: Buffer | string;
      headers: Record<string, string | string[] | undefined>;
    }): Promise<WebhookVerification> {
      const presented = headerValue(input.headers, PAYSTACK_SIGNATURE_HEADER);
      if (!presented) return { ok: false, reason: "missing_signature" };
      // A value that is not hex at all is malformed, not merely wrong. A valid
      // hex digest of the WRONG LENGTH — the SHA-256-for-SHA-512 bug — falls
      // through to the comparison below and is refused as a digest mismatch.
      if (!isHex(presented)) return { ok: false, reason: "malformed_signature" };

      // rawBody is used verbatim. It is NEVER parsed and re-serialised first.
      const expected = paystackDigest(input.rawBody, c.secretKey);
      if (!signatureMatches(expected, presented)) {
        return { ok: false, reason: "digest_mismatch" };
      }

      let payload: Record<string, unknown>;
      try {
        const text = Buffer.isBuffer(input.rawBody)
          ? input.rawBody.toString("utf8")
          : input.rawBody;
        const parsed = JSON.parse(text) as unknown;
        if (!parsed || typeof parsed !== "object") return { ok: false, reason: "malformed_body" };
        payload = parsed as Record<string, unknown>;
      } catch {
        return { ok: false, reason: "malformed_body" };
      }

      const event = decodeEvent(payload);
      if (!event) return { ok: false, reason: "unsupported_event" };
      return { ok: true, event };
    },

    chargeStoredAuthorization: chargeAuthorization,

    listEntitlements(reference: string): Promise<StoredEntitlement[]> {
      return entitlementsFor(reference);
    },

    async refund(req: RefundRequest): Promise<RefundResult> {
      const money = assertMoney(req.money, "refund.money");
      const res = await requestOrThrow(c, "POST", "/transaction/refund", {
        reference: req.reference,
        amount: money.amountMinor,
        currency: money.currency,
        ...(req.reason === undefined ? {} : { reason: req.reason }),
      });
      const ok = requireOk(res, "transaction/refund");
      if (!ok.ok) return { ok: false, reference: req.reference, reason: ok.error };
      const data = ok.data.data as Record<string, unknown> | undefined;
      const refundReference =
        typeof data?.reference === "string" && data.reference !== ""
          ? data.reference
          : `refund_${req.reference}`;
      const out = await refundPayment({
        provider: PAYSTACK_PROVIDER_ID,
        reference: req.reference,
        money,
        eventId: refundReference,
      });
      if (!out.applied) {
        return {
          ok: false,
          reference: req.reference,
          reason: out.duplicate ? "already_refunded" : "not_found",
        };
      }
      return { ok: true, reference: req.reference };
    },
  };
}

// ── webhook decoding ──────────────────────────────────────────────────────────

/**
 * `GET /transaction/verify/{reference}` against Paystack — the ONLY acceptable
 * authority on whether money moved. Exported so a route handler (and the gate)
 * can re-verify through the same code path the adapter uses, rather than
 * reimplementing it and getting the amount/currency checks wrong.
 */
export async function verifyTransactionServerSide(
  cfg: NormalizedConfig,
  reference: string,
): Promise<{ ok: true; status: string; money: Money } | { ok: false; error: string }> {
  const res = await request(cfg, "GET", `/transaction/verify/${encodeURIComponent(reference)}`);
  if (!res.ok) return { ok: false, error: res.error };
  const ok = requireOk(res.value, "transaction/verify");
  if (!ok.ok) return { ok: false, error: ok.error };
  const data = ok.data.data as Record<string, unknown> | undefined;
  if (!data) return { ok: false, error: "transaction/verify: no data" };
  const status = String(data.status ?? "");
  const amountMinor = toInt(data.amount);
  const currency = String(data.currency ?? "");
  if (amountMinor === null) return { ok: false, error: "transaction/verify: non-integer amount" };
  if (!/^[A-Za-z]{3}$/.test(currency))
    return { ok: false, error: "transaction/verify: malformed currency" };
  return { ok: true, status, money: { amountMinor, currency: currency.toUpperCase() } };
}

/** Normalised-config factory for callers that want `verifyTransactionServerSide`. */
export function paystackConfig(cfg: PaystackConfig): NormalizedConfig {
  return normalizeConfig(cfg);
}

/** Decode a Paystack event envelope into the provider-agnostic shape. */
export function decodeEvent(payload: Record<string, unknown>): ProviderEvent | null {
  const event = String(payload.event ?? "");
  const data = payload.data as Record<string, unknown> | undefined;
  if (!data) return null;

  const reference = typeof data.reference === "string" ? data.reference : "";
  if (reference === "") return null;
  const amountMinor = toInt(data.amount);
  if (amountMinor === null) return null;
  const currency = String(data.currency ?? "");
  if (!/^[A-Za-z]{3}$/.test(currency)) return null;
  const eventId = payload.id === undefined || payload.id === null ? "" : String(payload.id);
  if (eventId === "") return null;

  let kind: ProviderEvent["kind"];
  switch (event) {
    case "charge.success":
      kind = "charge.succeeded";
      break;
    case "charge.failed":
      kind = "charge.failed";
      break;
    case "refund.processed":
    case "refund.succeeded":
      kind = "refund.succeeded";
      break;
    default:
      return null;
  }

  return {
    eventId,
    kind,
    reference,
    money: { amountMinor, currency: currency.toUpperCase() },
    occurredAt: String(data.paid_at ?? data.created_at ?? new Date(0).toISOString()),
  };
}

/**
 * The browser-return handler. Deliberately ignores everything the browser
 * claims and re-verifies with Paystack directly: only
 * `status === "success"` AND amount AND currency all matching the recorded
 * intent settles the payment.
 *
 * `expected` is what WE asked for (from our own checkout record), never a
 * query parameter.
 */
export async function onCheckoutComplete(input: {
  reference: string;
  expected: Money;
  provider: PaymentProvider;
  /** Server-side re-verification, injected so the gate needs no network. */
  verify: (
    reference: string,
  ) => Promise<{ ok: true; status: string; money: Money } | { ok: false; error: string }>;
  entitlements?: StoredEntitlement[];
  /** What the browser *claimed*. Recorded for the audit trail, never trusted. */
  claimedStatus?: string | null;
}): Promise<
  | { ok: true; settled: boolean; reason?: "already_settled" }
  | {
      ok: false;
      reason:
        | "verification_failed"
        | "not_success"
        | "amount_mismatch"
        | "currency_mismatch"
        | "not_our_reference";
      detail?: string;
    }
> {
  const parsed = parseReference(input.reference);
  if (!parsed) return { ok: false, reason: "not_our_reference" };

  const verified = await input.verify(input.reference);
  if (!verified.ok) return { ok: false, reason: "verification_failed", detail: verified.error };

  // The browser's own claim is ignored on purpose; only Paystack's answer counts.
  if (verified.status !== "success") {
    return { ok: false, reason: "not_success", detail: verified.status };
  }
  if (verified.money.amountMinor !== input.expected.amountMinor) {
    return {
      ok: false,
      reason: "amount_mismatch",
      detail: `${verified.money.amountMinor} != ${input.expected.amountMinor}`,
    };
  }
  if (verified.money.currency !== input.expected.currency.toUpperCase()) {
    return { ok: false, reason: "currency_mismatch", detail: verified.money.currency };
  }

  const settled = await settlePayment({
    provider: input.provider.id,
    orgId: parsed.orgId,
    reference: input.reference,
    money: verified.money,
    status: "success",
    // The provider event id for a browser-return settlement is the reference
    // itself: one purchase is one credit no matter how many times the buyer
    // refreshes the return page.
    eventId: `paystack:return:${input.reference}`,
    entitlements: input.entitlements,
    purpose: parsed.purpose,
  });
  if (!settled.applied) return { ok: true, settled: false, reason: "already_settled" };
  return { ok: true, settled: true };
}

/** Build a stored authorization from our own record of a checkout. */
export function storedAuthorizationFrom(input: {
  authorizationCode: string;
  email: string;
  reference?: string;
}): StoredAuthorization {
  return {
    authorizationCode: input.authorizationCode,
    email: input.email,
    ...(input.reference === undefined ? {} : { reference: input.reference }),
  };
}

/** Read the secret key from the environment, test keys enforced. */
export function paystackSecretKey(): string {
  const key = process.env[SECRET_KEY_ENV];
  if (!key) throw new Error(`${SECRET_KEY_ENV} is not configured`);
  return key;
}
