import "server-only";
/**
 * `PaymentProvider` port (WP-13).
 *
 * This file is the ONLY place domain code talks to money movement. Nothing
 * outside `src/lib/payments/*` may import a gateway type: no `paystack`,
 * no `flutterwave`, no `authorization_code`, no `x-paystack-signature`. A new
 * gateway is a new adapter file and zero changes to callers — which is the
 * point of the port.
 *
 * ## Contracts that must not move
 *
 *   - **Money is integer minor units.** `Money.amountMinor` is validated at the
 *     port boundary (`assertMoney`), never at the gateway's boundary, so a
 *     float can never enter a `PaymentRecord`.
 *   - **A webhook is a claim, not a fact.** `verifyWebhook` proves the bytes
 *     came from the gateway. It does NOT prove the payment succeeded; the
 *     adapter must re-verify server-side and only then call `settlePayment`.
 *   - **One effect per (reference, eventId).** `settlePayment` is the single
 *     writer of `PaymentRecord` and the single caller of the ledger top-up, and
 *     both are guarded by unique indexes.
 */

import { db } from "@/lib/db";
import { appendInTransaction, refund as ledgerRefund } from "@/lib/billing/ledger";

export type Money = {
  /** Integer minor units (fils, kobo, cents). Never a float. */
  amountMinor: number;
  /** ISO 4217. Compared case-insensitively, stored upper-case. */
  currency: string;
};

/** A stored card authorization usable for later charges (computed overage). */
export type StoredAuthorization = {
  /** Opaque, provider-scoped. Never logged. */
  authorizationCode: string;
  email: string;
  /** Our reference the authorization was taken under, for reconciliation. */
  reference?: string;
};

export type CheckoutRequest = {
  orgId: string;
  purpose: string;
  money: Money;
  email: string;
  /** Where the buyer returns after paying. Defaults to the app's return URL. */
  returnUrl?: string;
  /** Idempotency token supplied by the caller; the adapter maps it to a reference. */
  requestKey: string;
};

export type CheckoutSession = {
  /** The provider's redirect URL. */
  url: string;
  accessCode: string;
  /** OUR reference, generated by us. This is the `PaymentRecord.reference`. */
  reference: string;
};

export type ChargeRequest = {
  orgId: string;
  authorization: StoredAuthorization;
  money: Money;
  purpose: string;
  requestKey: string;
};

export type ChargeResult =
  | { ok: true; reference: string; verified: true; raw?: unknown }
  | { ok: false; reference: string; reason: string; raw?: unknown };

/** What a verified gateway event actually asserts. */
export type ProviderEvent = {
  /** Gateway event id. Paired with `reference` it dedupes settlement. */
  eventId: string;
  kind: "charge.succeeded" | "charge.failed" | "refund.succeeded";
  /** OUR reference, as generated at checkout. */
  reference: string;
  money: Money;
  /** ISO-8601, as reported by the gateway. */
  occurredAt: string;
  /** Anything the adapter needs downstream. Provider-shaped, never persisted raw. */
  metadata?: Record<string, unknown>;
};

export type WebhookRejection =
  | "missing_signature"
  | "malformed_signature"
  | "digest_mismatch"
  | "malformed_body"
  | "unsupported_event";

export type WebhookVerification =
  { ok: true; event: ProviderEvent } | { ok: false; reason: WebhookRejection; detail?: string };

export type RefundRequest = {
  reference: string;
  money: Money;
  reason?: string;
};

export type RefundResult =
  | { ok: true; reference: string; raw?: unknown }
  | { ok: false; reference: string; reason: string; raw?: unknown };

/**
 * One entitlement granted by a payment. `units` is an integer count (never a
 * float) so the caller can translate it into ledger units without rounding.
 */
export type StoredEntitlement = {
  key: string;
  label?: string;
  units?: number;
  metadata?: Record<string, unknown>;
};

/**
 * What actually lands in `PaymentRecord.entitlementsJson`.
 *
 * It is an envelope, not a bare array, because dual control has to survive a
 * process restart: `recordedBy` is the operator who entered the payment and is
 * what `verify` compares against `verifiedBy` to enforce that the recorder can
 * never be the verifier. Keeping it in the DB (rather than in memory) is what
 * makes the separation enforceable.
 */
export type EntitlementEnvelope = {
  version: 1;
  entitlements: StoredEntitlement[];
  recordedBy?: string;
  verifiedBy?: string;
  eventId?: string;
  purpose?: string;
  note?: string;
};

export interface PaymentProvider {
  /** Stable adapter id written to `PaymentRecord.provider`. */
  readonly id: string;

  /** Start a payment. Returns a redirect URL; the buyer leaves the app. */
  createCheckout(req: CheckoutRequest): Promise<CheckoutSession>;

  /**
   * Prove the webhook bytes are authentic and decode them. Does NOT settle —
   * call `settlePayment` only after a server-side re-verification.
   */
  verifyWebhook(input: {
    /** The EXACT bytes received. Never re-serialised. */
    rawBody: Buffer | string;
    headers: Record<string, string | string[] | undefined>;
  }): Promise<WebhookVerification>;

  /** Charge a previously stored authorization (computed overage). */
  chargeStoredAuthorization(req: ChargeRequest): Promise<ChargeResult>;

  /** Entitlements a settled reference granted. */
  listEntitlements(reference: string): Promise<StoredEntitlement[]>;

  /** Give money back. */
  refund(req: RefundRequest): Promise<RefundResult>;
}

// ── shared port helpers ───────────────────────────────────────────────────────

export function assertMoney(money: Money, name = "money"): Money {
  if (!money || typeof money !== "object") throw new TypeError(`${name} is required`);
  const { amountMinor, currency } = money;
  if (typeof amountMinor !== "number" || !Number.isInteger(amountMinor)) {
    throw new TypeError(
      `${name}.amountMinor must be an integer minor-unit value (got ${String(amountMinor)})`,
    );
  }
  if (!Number.isSafeInteger(amountMinor)) {
    throw new RangeError(`${name}.amountMinor exceeds the safe integer range`);
  }
  if (typeof currency !== "string" || !/^[A-Za-z]{3}$/.test(currency)) {
    throw new TypeError(
      `${name}.currency must be an ISO-4217 alpha-3 code (got ${String(currency)})`,
    );
  }
  return { amountMinor, currency: currency.toUpperCase() };
}

/** Build the `entitlementsJson` envelope deterministically. */
export function encodeEntitlements(envelope: EntitlementEnvelope): string {
  if (envelope.version !== 1) throw new TypeError("entitlement envelope version must be 1");
  return JSON.stringify({
    version: 1,
    entitlements: (envelope.entitlements ?? []).map((e) => ({
      key: e.key,
      ...(e.label === undefined ? {} : { label: e.label }),
      ...(e.units === undefined
        ? {}
        : { units: assertNonNegativeInt(e.units, "entitlement.units") }),
      ...(e.metadata === undefined ? {} : { metadata: e.metadata }),
    })),
    ...(envelope.recordedBy === undefined ? {} : { recordedBy: envelope.recordedBy }),
    ...(envelope.verifiedBy === undefined ? {} : { verifiedBy: envelope.verifiedBy }),
    ...(envelope.eventId === undefined ? {} : { eventId: envelope.eventId }),
    ...(envelope.purpose === undefined ? {} : { purpose: envelope.purpose }),
    ...(envelope.note === undefined ? {} : { note: envelope.note }),
  });
}

function assertNonNegativeInt(v: number, name: string): number {
  if (typeof v !== "number" || !Number.isInteger(v) || v < 0) {
    throw new TypeError(`${name} must be a non-negative integer`);
  }
  return v;
}

/** Read the envelope back. A row with no/!parseable envelope yields `[]`. */
export function decodeEntitlements(json: string | null | undefined): EntitlementEnvelope {
  const empty: EntitlementEnvelope = { version: 1, entitlements: [] };
  if (!json) return empty;
  try {
    const parsed = JSON.parse(json) as Partial<EntitlementEnvelope>;
    if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.entitlements)) return empty;
    return { ...empty, ...parsed, entitlements: parsed.entitlements } as EntitlementEnvelope;
  } catch {
    return empty;
  }
}

export type SettleInput = {
  provider: string;
  orgId: string;
  /** OUR reference (the `PaymentRecord.reference` unique key). */
  reference: string;
  money: Money;
  status: "success" | "failed";
  /** Gateway event id; the ledger top-up's dedupe token. */
  eventId: string;
  entitlements?: StoredEntitlement[];
  purpose?: string;
  note?: string;
  /** Operator id for a manually verified payment. Gateway settlements record "gateway". */
  verifiedBy?: string;
  /**
   * Who entered the payment. Carried through settlement so the dual-control
   * evidence (recorder != verifier) survives in the settled row — overwriting
   * the envelope without it would erase the very fact the control depends on.
   */
  recordedBy?: string;
};

export type SettleResult = {
  /** False when this (reference, eventId) had already been applied. */
  applied: boolean;
  paymentId: string;
  unitsCredited: number;
  duplicate: boolean;
};

/**
 * The ONLY writer of a successful `PaymentRecord`, and the only bridge from
 * money to prepaid units.
 *
 * Three independent guards make a replayed webhook (or a double-tapped verify
 * button) a no-op:
 *
 *   1. `PaymentRecord.reference` is UNIQUE — the insert can only win once.
 *   2. A row that already exists is flipped with a CONDITIONAL update
 *      (`WHERE status IN ('pending','failed')`). Two verifiers racing on one
 *      pending row therefore cannot both settle it: exactly one UPDATE
 *      returns a row.
 *   3. The ledger top-up is idempotent on the gateway event id, so even a
 *      replay that somehow reached the credit step twice writes one row.
 *
 * The payment row and the ledger credit commit together, so a credit with no
 * payment record (or the reverse) is not reachable.
 */
export async function settlePayment(input: SettleInput): Promise<SettleResult> {
  const money = assertMoney(input.money, "settlePayment.money");
  if (!input.reference) throw new TypeError("settlePayment.reference is required");
  if (!input.eventId) throw new TypeError("settlePayment.eventId is required");

  if (input.status === "failed") {
    // Never downgrade a settled payment: a later "failed" event for a reference
    // we already credited must not un-credit it.
    const paymentId = `pay_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 12)}`;
    const inserted = await db.$queryRaw<{ id: string }[]>`
      INSERT INTO "PaymentRecord"
        ("id", "orgId", "provider", "reference", "amountMinor", "currency", "status", "createdAt")
      VALUES (${paymentId}, ${input.orgId ?? null}, ${input.provider}, ${input.reference},
              ${money.amountMinor}, ${money.currency}, 'failed', ${new Date()})
      ON CONFLICT ("reference") DO NOTHING
      RETURNING "id"
    `;
    return {
      applied: inserted.length === 1,
      paymentId: inserted[0]?.id ?? "",
      unitsCredited: 0,
      duplicate: inserted.length === 0,
    };
  }

  const entitlements = input.entitlements ?? [];
  // Credits are paid units: the payment amount in minor currency units plus any
  // explicit entitlement quantities. Integers only — no float arithmetic.
  const unitsCredited = entitlements.reduce((acc, e) => acc + (e.units ?? 0), money.amountMinor);
  const envelopeJson = encodeEntitlements({
    version: 1,
    entitlements,
    eventId: input.eventId,
    ...(input.purpose === undefined ? {} : { purpose: input.purpose }),
    ...(input.note === undefined ? {} : { note: input.note }),
    ...(input.recordedBy === undefined ? {} : { recordedBy: input.recordedBy }),
    ...(input.verifiedBy === undefined ? {} : { verifiedBy: input.verifiedBy }),
  });
  const verifiedBy = input.verifiedBy ?? "gateway";
  const now = new Date();

  return db.$transaction(
    async (tx) => {
      const paymentId = `pay_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 12)}`;
      const inserted = await tx.$queryRaw<{ id: string }[]>`
        INSERT INTO "PaymentRecord"
          ("id", "orgId", "provider", "reference", "amountMinor", "currency", "status",
           "entitlementsJson", "verifiedAt", "verifiedBy", "createdAt")
        VALUES (${paymentId}, ${input.orgId ?? null}, ${input.provider}, ${input.reference},
                ${money.amountMinor}, ${money.currency}, 'success',
                ${envelopeJson}, ${now}, ${verifiedBy}, ${now})
        ON CONFLICT ("reference") DO NOTHING
        RETURNING "id"
      `;

      let settledId: string;
      let settled: boolean;
      if (inserted.length === 1) {
        // `inserted.length === 1` is the guard on this branch, so index 0 is the
        // single row the INSERT ... RETURNING produced.
        settledId = inserted[0]!.id;
        settled = true;
      } else {
        // The reference already exists (manual invoice: recorded, then verified;
        // gateway: a replayed webhook). Flip it only if it is still unsettled —
        // one atomic conditional UPDATE, so concurrent verifiers cannot both win.
        const flipped = await tx.$queryRaw<{ id: string }[]>`
          UPDATE "PaymentRecord"
             SET status = 'success', "verifiedAt" = ${now}, "verifiedBy" = ${verifiedBy},
                 "entitlementsJson" = ${envelopeJson}
           WHERE "reference" = ${input.reference} AND status IN ('pending', 'failed')
          RETURNING "id"
        `;
        if (flipped.length === 1) {
          // Same guard: the conditional UPDATE returned exactly one row.
          settledId = flipped[0]!.id;
          settled = true;
        } else {
          const existing = await tx.paymentRecord.findUnique({
            where: { reference: input.reference },
            select: { id: true },
          });
          return {
            applied: false,
            paymentId: existing?.id ?? "",
            unitsCredited: 0,
            duplicate: true,
          };
        }
      }

      // Idempotent on the gateway event id, so a replay that somehow slipped
      // past the reference check still credits nothing.
      //
      // Runs INSIDE this transaction via appendInTransaction: opening a second
      // transaction here would let the credit commit while this one rolls back
      // (or the reverse), leaving a balance that disagrees with the payment
      // record justifying it.
      const credit = await appendInTransaction(tx, {
        orgId: input.orgId,
        units: unitsCredited,
        eventId: input.eventId,
        reason: `${input.provider}:${input.reference}`,
      });

      return {
        applied: true,
        paymentId: settledId,
        unitsCredited: credit.ok && !credit.duplicate ? unitsCredited : 0,
        duplicate: settled && credit.ok && credit.duplicate,
      };
    },
    { maxWait: 30_000, timeout: 30_000 },
  );
}

/**
 * Reverse a settled payment: mark it refunded and write the matching ledger
 * `refund` row, so `available` falls by exactly the credited units.
 */
export async function refundPayment(input: {
  provider: string;
  reference: string;
  money: Money;
  eventId: string;
  reason?: string;
}): Promise<SettleResult> {
  const money = assertMoney(input.money, "refundPayment.money");
  const existing = await db.paymentRecord.findUnique({
    where: { reference: input.reference },
    select: { id: true, orgId: true, status: true },
  });
  if (!existing) {
    return { applied: false, paymentId: "", unitsCredited: 0, duplicate: false };
  }
  if (existing.status === "refunded") {
    return { applied: false, paymentId: existing.id, unitsCredited: 0, duplicate: true };
  }

  await db.paymentRecord.update({
    where: { id: existing.id },
    data: { status: "refunded" },
  });
  if (existing.orgId) {
    await ledgerRefund({
      orgId: existing.orgId,
      units: money.amountMinor,
      eventId: input.eventId,
      reason: input.reason ?? `${input.provider}:${input.reference}:refund`,
    });
  }
  return { applied: true, paymentId: existing.id, unitsCredited: 0, duplicate: false };
}

/** Entitlements granted by a settled reference. */
export async function entitlementsFor(reference: string): Promise<StoredEntitlement[]> {
  const row = await db.paymentRecord.findUnique({
    where: { reference },
    select: { entitlementsJson: true },
  });
  return decodeEntitlements(row?.entitlementsJson).entitlements;
}
